
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVjb0BlY28uY29tIiwiaWF0IjoxNjU1NDIzMzM1LCJleHAiOjE2NTU2ODI1MzV9.BnwLYm6GakywrS2N3DGNziF_mhf4cgJ1H44oRfTCEwk 

### Create a set
POST {{host}}/api/set
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Conocimiento de Incendios",
  "description": "This is my set",
  "isPublic": true
}

### Get sets
GET {{host}}/api/set
Content-Type: application/json
Authorization: Bearer {{token}}

### Update a set
PUT {{host}}/api/set
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "62abc1a4e21b8d8b8ae02b5e",
  "name": "My Set Updated",
  "description": "This is my set"
}

### Delete a set
DELETE {{host}}/api/set
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "62aa6a37bd5d91c6a3bac71a"
}

### Get the public set
GET {{host}}/api/set/public
Content-Type: application/json